name: Run Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set installer.sh as executable
        run: chmod +x installer.sh

      - name: Run installer.sh
        run: ./installer.sh